### ISSUE TITLE
Problems with path replace in CSS

### ISSUE THREAD

**Issue by zkrat** [chemix/Nette-Grunt#1]
There is a problem when you have css in multiple directories with links to images. Minification does not change directories path to image files in CSS.

**Comment by chemix** [comment]
Sorry, this example works only with one folder for styles. For more folders look at another grunt plugin for css minification with support for this. 

For example: https://github.com/gruntjs/grunt-contrib-copy  has option for this: 

```
// flattens results to a single level
{expand: true, flatten: true, src: ['path/**'], dest: 'dest/', filter: 'isFile'},
```
